### ISSUE TITLE
Unable to push on this repo

### ISSUE THREAD

**Issue by MiguelDRPina** [lardemua/atom_rviz_plugin#12]
Hi @miguelriemoliveira ,
I just wanted to test to see why that data_collect wasn't working earlier and it worked when I tried again. But I did what you suggested anyways and removed the previous package and cloned this repo and when I was trying to commit, I wasn't able to.

![Screenshot from 2021-05-04 18-18-57](https://user-images.githubusercontent.com/73201389/117043810-9c151080-ad05-11eb-83d7-5cc092c442f3.png)

Could you check the permissions?

**Comment by miguelriemoliveira** [comment]
Hi @MiguelDRPina ,

please try again.  I changed your role from admin to write ... but that should have not been the problem ...

**Comment by miguelriemoliveira** [comment]
Also, can you try to push using the terminal and paste the output here?

**Comment by MiguelDRPina** [comment]
Hi @miguelriemoliveira ,

I think it was some problem with the github authentication in the IDE, it works now. Thank you. Closing the issue.
